### ISSUE TITLE
Create Questions struct

### ISSUE THREAD

**Issue by gabucito** [SwiftSergio/rust-regex-pro#5]
I think we need to create a question struct.  Something like the following:
```
struct Question {
    explanation: String,
    search_string: String,
    points: i32,
    level: Level,
}

impl Question {
    pub fn ask_user_question(&self) {
        // ...
    }
}
```

This way we can separate questions by their level and maybe have each question award different points.
We could also just remove points and award depending on their level instead.

**Comment by SwiftSergio** [comment]
Agreed.

**Comment by SwiftSergio** [comment]
Although I think the type for `explanation` should be `&'static str` as the values will be known at compile time.

**Comment by SwiftSergio** [comment]
I started working on implementing the `Question` struct.
